function daysAgo(n) {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

export const demoProfile = {
  id: 1,
  name: 'Demo Ranger',
  email: 'demo@example.org',
  role: 'admin',
  org_id: 1,
  organization: { id: 1, name: 'Canopy Demo Org' },
}

export const demoRegions = [
  {
    id: 1, org_id: 1,
    name: 'Sector Araguaia',
    description: 'Eastern Pará — primary logging pressure vector.',
    boundary: null,
    created_at: daysAgo(90), updated_at: daysAgo(1),
  },
  {
    id: 2, org_id: 1,
    name: 'Sector Xingu',
    description: 'Terra do Meio Ecological Station buffer zone.',
    boundary: null,
    created_at: daysAgo(85), updated_at: daysAgo(2),
  },
  {
    id: 3, org_id: 1,
    name: 'Sector Tapajós',
    description: 'Tapajós National Forest — southern edge surveillance.',
    boundary: null,
    created_at: daysAgo(80), updated_at: daysAgo(3),
  },
]

export const demoSensors = [
  {
    id: 1, org_id: 1, region_id: 1,
    name: 'ARA-01', device_type: 'forest-listening-unit',
    location: { lat: -9.831, lon: -50.487 },
    status: 'online', last_heard_at: daysAgo(0),
  },
  {
    id: 2, org_id: 1, region_id: 1,
    name: 'ARA-02', device_type: 'forest-listening-unit',
    location: { lat: -9.756, lon: -50.612 },
    status: 'offline', last_heard_at: daysAgo(4),
  },
  {
    id: 3, org_id: 1, region_id: 2,
    name: 'XIK-01', device_type: 'acoustic-logger',
    location: { lat: -7.314, lon: -52.391 },
    status: 'online', last_heard_at: daysAgo(0),
  },
  {
    id: 4, org_id: 1, region_id: 2,
    name: 'XIK-02', device_type: 'acoustic-logger',
    location: { lat: -7.488, lon: -52.255 },
    status: 'online', last_heard_at: daysAgo(0),
  },
  {
    id: 5, org_id: 1, region_id: 3,
    name: 'TAP-01', device_type: 'forest-listening-unit',
    location: { lat: -5.902, lon: -57.143 },
    status: 'online', last_heard_at: daysAgo(0),
  },
]

export const demoSatelliteChanges = [
  // Araguaia — progressive degradation
  {
    id: 1, org_id: 1, region_id: 1, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.31, confidence: 0.88,
    latitude: -9.829, longitude: -50.491,
    description: 'Early canopy thinning, northwest Araguaia grid A3',
    metadata: { baseline_ndvi: 0.74, recent_ndvi: 0.61, ndvi_delta: -0.13, ingestion_batch_id: 1 },
    created_at: daysAgo(78), updated_at: daysAgo(78),
  },
  {
    id: 2, org_id: 1, region_id: 1, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.44, confidence: 0.91,
    latitude: -9.834, longitude: -50.484,
    description: 'Canopy loss accelerating — grid A3 southeast corner',
    metadata: { baseline_ndvi: 0.74, recent_ndvi: 0.52, ndvi_delta: -0.22, ingestion_batch_id: 1 },
    created_at: daysAgo(52), updated_at: daysAgo(52),
  },
  {
    id: 3, org_id: 1, region_id: 1, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.63, confidence: 0.93,
    latitude: -9.841, longitude: -50.478,
    description: 'Significant vegetation loss, probable road clearing',
    metadata: { baseline_ndvi: 0.74, recent_ndvi: 0.41, ndvi_delta: -0.33, ingestion_batch_id: 1 },
    created_at: daysAgo(28), updated_at: daysAgo(28),
  },
  {
    id: 4, org_id: 1, region_id: 1, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.79, confidence: 0.95,
    latitude: -9.847, longitude: -50.471,
    description: 'Critical deforestation front — 2.1 ha cleared in 14 days',
    metadata: { baseline_ndvi: 0.74, recent_ndvi: 0.29, ndvi_delta: -0.45, ingestion_batch_id: 1 },
    created_at: daysAgo(7), updated_at: daysAgo(7),
  },
  // Xingu — Sentinel-2 + CSV
  {
    id: 5, org_id: 1, region_id: 2, source: 'sentinel_2', change_type: 'canopy_loss',
    severity_score: 0.38, confidence: 0.82,
    latitude: -7.318, longitude: -52.388,
    description: 'Sentinel-2 canopy loss detection, Xingu buffer boundary',
    metadata: { baseline_ndvi: 0.71, recent_ndvi: 0.58, ndvi_delta: -0.13, ingestion_batch_id: 2 },
    created_at: daysAgo(68), updated_at: daysAgo(68),
  },
  {
    id: 6, org_id: 1, region_id: 2, source: 'sentinel_2', change_type: 'canopy_loss',
    severity_score: 0.52, confidence: 0.87,
    latitude: -7.325, longitude: -52.402,
    description: 'Expanding clearing footprint — Xingu grid B7',
    metadata: { baseline_ndvi: 0.71, recent_ndvi: 0.47, ndvi_delta: -0.24, ingestion_batch_id: 2 },
    created_at: daysAgo(41), updated_at: daysAgo(41),
  },
  {
    id: 7, org_id: 1, region_id: 2, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.67, confidence: 0.90,
    latitude: -7.491, longitude: -52.251,
    description: 'High-severity drop near XIK-02 — possible cattle pasture conversion',
    metadata: { baseline_ndvi: 0.68, recent_ndvi: 0.38, ndvi_delta: -0.30, ingestion_batch_id: 2 },
    created_at: daysAgo(19), updated_at: daysAgo(19),
  },
  {
    id: 8, org_id: 1, region_id: 2, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.84, confidence: 0.94,
    latitude: -7.495, longitude: -52.245,
    description: 'Critical: 4.3 ha bare soil visible in latest mosaic',
    metadata: { baseline_ndvi: 0.68, recent_ndvi: 0.22, ndvi_delta: -0.46, ingestion_batch_id: 2 },
    created_at: daysAgo(5), updated_at: daysAgo(5),
  },
  // Tapajós — park boundary surveillance
  {
    id: 9, org_id: 1, region_id: 3, source: 'sentinel_2', change_type: 'canopy_loss',
    severity_score: 0.29, confidence: 0.80,
    latitude: -5.907, longitude: -57.138,
    description: 'Low-severity fragmentation near Tapajós park boundary',
    metadata: { baseline_ndvi: 0.76, recent_ndvi: 0.65, ndvi_delta: -0.11, ingestion_batch_id: 3 },
    created_at: daysAgo(72), updated_at: daysAgo(72),
  },
  {
    id: 10, org_id: 1, region_id: 3, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.41, confidence: 0.85,
    latitude: -5.899, longitude: -57.151,
    description: 'Selective logging trail identified — Tapajós southwest',
    metadata: { baseline_ndvi: 0.76, recent_ndvi: 0.55, ndvi_delta: -0.21, ingestion_batch_id: 3 },
    created_at: daysAgo(44), updated_at: daysAgo(44),
  },
  {
    id: 11, org_id: 1, region_id: 3, source: 'csv_ndvi', change_type: 'ndvi_drop',
    severity_score: 0.55, confidence: 0.89,
    latitude: -5.895, longitude: -57.162,
    description: 'Sustained canopy loss — 3 consecutive passes confirm activity',
    metadata: { baseline_ndvi: 0.76, recent_ndvi: 0.45, ndvi_delta: -0.31, ingestion_batch_id: 3 },
    created_at: daysAgo(21), updated_at: daysAgo(21),
  },
  {
    id: 12, org_id: 1, region_id: 3, source: 'sentinel_2', change_type: 'canopy_loss',
    severity_score: 0.72, confidence: 0.92,
    latitude: -5.891, longitude: -57.170,
    description: 'High severity — chainsaws and vehicle audio corroborating',
    metadata: { baseline_ndvi: 0.76, recent_ndvi: 0.34, ndvi_delta: -0.42, ingestion_batch_id: 3 },
    created_at: daysAgo(3), updated_at: daysAgo(3),
  },
]

export const demoAlerts = [
  // === OPEN-SET ANOMALY DETECTOR ===
  // Catch-all acoustic detector: flags deviation from normal forest background,
  // then reports a likelihood of what the anomaly seems to be (incl. "unknown").
  {
    id: 101, org_id: 1, type: 'anomaly', status: 'open', priority: 'high',
    description: 'Anomalous sound detected (94%) — likely chainsaw (71%) near ARA-01.',
    location: { lat: -9.833, lon: -50.486 },
    sensor_id: 1, region_id: 1,
    classifier_label: 'chainsaw', classifier_confidence: 0.71,
    classifier_model_version: 'anomaly-v1',
    metadata: {
      anomaly_score: 0.94, is_anomaly: true, predicted_kind: 'chainsaw',
      likelihoods: { chainsaw: 0.71, vehicle: 0.12, unknown: 0.17 },
      model_version: 'anomaly-v1',
    },
    created_at: daysAgo(1), updated_at: daysAgo(1),
  },
  {
    id: 102, org_id: 1, type: 'anomaly', status: 'investigating', priority: 'medium',
    description: 'Anomalous sound detected (88%) — unrecognized source (unknown 64%) near XIK-01.',
    location: { lat: -11.214, lon: -53.121 },
    sensor_id: 3, region_id: 2,
    classifier_label: 'unknown', classifier_confidence: 0.64,
    classifier_model_version: 'anomaly-v1',
    metadata: {
      anomaly_score: 0.88, is_anomaly: true, predicted_kind: 'unknown',
      likelihoods: { unknown: 0.64, vehicle: 0.21, chainsaw: 0.15 },
      model_version: 'anomaly-v1',
    },
    created_at: daysAgo(2), updated_at: daysAgo(1),
  },
  // === ARAGUAIA THREAD ===
  {
    id: 1, org_id: 1, type: 'audio', status: 'resolved', priority: 'medium',
    description: "Audio classifier detected 'chainsaw' with 78% confidence near ARA-01.",
    location: { lat: -9.831, lon: -50.487 },
    sensor_id: 1, region_id: 1,
    classifier_label: 'chainsaw', classifier_confidence: 0.78,
    classifier_model_version: 'placeholder-v0',
    metadata: {},
    created_at: daysAgo(77), updated_at: daysAgo(74),
  },
  {
    id: 2, org_id: 1, type: 'fusion', status: 'resolved', priority: 'medium',
    description: "Fusion alert: acoustic 'chainsaw' at ARA-01 corroborated by NDVI drop in grid A3 (score 0.54).",
    location: { lat: -9.830, lon: -50.489 },
    sensor_id: 1, region_id: 1,
    classifier_label: 'chainsaw', classifier_confidence: 0.78,
    classifier_model_version: 'placeholder-v0',
    metadata: {
      acoustic_alert_id: 1, satellite_change_id: 1,
      acoustic_confidence: 0.78, acoustic_confidence_threshold: 0.65,
      acoustic_suppressed: false, acoustic_weight: 0.45,
      satellite_severity_score: 0.31, satellite_confidence: 0.88,
      distance_meters: 21.4,
      fusion_score: 0.541, fusion_scoring_mode: 'acoustic_satellite',
      fusion_rule_version: 'rule-fusion-v2',
      temporal_decay: 0.91, spatial_decay: 0.88,
      time_decay_halflife_days: 7.0, spatial_sigma_meters: 200.0,
      corroborating_change_count: 1, source_quality_multiplier: 1.05,
      baseline_ndvi: 0.74, recent_ndvi: 0.61, ndvi_delta: -0.13, ingestion_batch_id: 1,
    },
    created_at: daysAgo(76), updated_at: daysAgo(70),
  },
  {
    id: 3, org_id: 1, type: 'audio', status: 'acknowledged', priority: 'high',
    description: "Audio classifier detected 'vehicle' (logging truck) with 85% confidence near ARA-01.",
    location: { lat: -9.832, lon: -50.485 },
    sensor_id: 1, region_id: 1,
    classifier_label: 'vehicle', classifier_confidence: 0.85,
    classifier_model_version: 'placeholder-v0',
    metadata: {},
    created_at: daysAgo(27), updated_at: daysAgo(25),
  },
  {
    id: 4, org_id: 1, type: 'fusion', status: 'investigating', priority: 'critical',
    description: "CRITICAL: Chainsaw + vehicle acoustic cluster corroborated by 2 satellite changes (score 0.87). Active deforestation front confirmed.",
    location: { lat: -9.838, lon: -50.482 },
    sensor_id: 1, region_id: 1,
    classifier_label: 'chainsaw', classifier_confidence: 0.91,
    classifier_model_version: 'placeholder-v0',
    metadata: {
      acoustic_alert_id: 3, satellite_change_id: 4,
      acoustic_confidence: 0.91, acoustic_confidence_threshold: 0.65,
      acoustic_suppressed: false, acoustic_weight: 0.45,
      satellite_severity_score: 0.79, satellite_confidence: 0.95,
      distance_meters: 14.2,
      fusion_score: 0.874, fusion_scoring_mode: 'acoustic_satellite',
      fusion_rule_version: 'rule-fusion-v2',
      temporal_decay: 0.97, spatial_decay: 0.96,
      time_decay_halflife_days: 7.0, spatial_sigma_meters: 200.0,
      corroborating_change_count: 2, source_quality_multiplier: 1.15,
      baseline_ndvi: 0.74, recent_ndvi: 0.29, ndvi_delta: -0.45, ingestion_batch_id: 1,
    },
    created_at: daysAgo(6), updated_at: daysAgo(1),
  },

  // === XINGU THREAD ===
  {
    id: 5, org_id: 1, type: 'audio', status: 'open', priority: 'high',
    description: "Audio classifier detected 'gunshot' with 88% confidence near XIK-01. Possible illegal hunting or land conflict.",
    location: { lat: -7.316, lon: -52.389 },
    sensor_id: 3, region_id: 2,
    classifier_label: 'gunshot', classifier_confidence: 0.88,
    classifier_model_version: 'placeholder-v0',
    metadata: {},
    created_at: daysAgo(40), updated_at: daysAgo(40),
  },
  {
    id: 6, org_id: 1, type: 'fusion', status: 'acknowledged', priority: 'high',
    description: "Fusion alert: gunshot event at XIK-01 spatially coincides with expanding canopy clearance (score 0.69).",
    location: { lat: -7.319, lon: -52.396 },
    sensor_id: 3, region_id: 2,
    classifier_label: 'gunshot', classifier_confidence: 0.88,
    classifier_model_version: 'placeholder-v0',
    metadata: {
      acoustic_alert_id: 5, satellite_change_id: 6,
      acoustic_confidence: 0.88, acoustic_confidence_threshold: 0.65,
      acoustic_suppressed: false, acoustic_weight: 0.45,
      satellite_severity_score: 0.52, satellite_confidence: 0.87,
      distance_meters: 38.1,
      fusion_score: 0.692, fusion_scoring_mode: 'acoustic_satellite',
      fusion_rule_version: 'rule-fusion-v2',
      temporal_decay: 0.85, spatial_decay: 0.79,
      time_decay_halflife_days: 7.0, spatial_sigma_meters: 200.0,
      corroborating_change_count: 1, source_quality_multiplier: 1.08,
      baseline_ndvi: 0.71, recent_ndvi: 0.47, ndvi_delta: -0.24, ingestion_batch_id: 2,
    },
    created_at: daysAgo(39), updated_at: daysAgo(35),
  },
  {
    id: 7, org_id: 1, type: 'audio', status: 'open', priority: 'high',
    description: "Audio classifier detected 'chainsaw' with 92% confidence at XIK-02. Continuous operation >20 min.",
    location: { lat: -7.490, lon: -52.253 },
    sensor_id: 4, region_id: 2,
    classifier_label: 'chainsaw', classifier_confidence: 0.92,
    classifier_model_version: 'placeholder-v0',
    metadata: {},
    created_at: daysAgo(18), updated_at: daysAgo(18),
  },
  {
    id: 8, org_id: 1, type: 'fusion', status: 'open', priority: 'critical',
    description: "CRITICAL: Continuous chainsaw at XIK-02 fused with 84% NDVI severity. Immediate intervention required (score 0.91).",
    location: { lat: -7.492, lon: -52.248 },
    sensor_id: 4, region_id: 2,
    classifier_label: 'chainsaw', classifier_confidence: 0.92,
    classifier_model_version: 'placeholder-v0',
    metadata: {
      acoustic_alert_id: 7, satellite_change_id: 8,
      acoustic_confidence: 0.92, acoustic_confidence_threshold: 0.65,
      acoustic_suppressed: false, acoustic_weight: 0.45,
      satellite_severity_score: 0.84, satellite_confidence: 0.94,
      distance_meters: 9.7,
      fusion_score: 0.913, fusion_scoring_mode: 'acoustic_satellite',
      fusion_rule_version: 'rule-fusion-v2',
      temporal_decay: 0.98, spatial_decay: 0.98,
      time_decay_halflife_days: 7.0, spatial_sigma_meters: 200.0,
      corroborating_change_count: 2, source_quality_multiplier: 1.18,
      baseline_ndvi: 0.68, recent_ndvi: 0.22, ndvi_delta: -0.46, ingestion_batch_id: 2,
    },
    created_at: daysAgo(4), updated_at: daysAgo(4),
  },

  // === TAPAJÓS THREAD ===
  {
    id: 9, org_id: 1, type: 'audio', status: 'resolved', priority: 'low',
    description: "Audio classifier detected 'fire_crackle' with 71% confidence near TAP-01. Likely controlled burn.",
    location: { lat: -5.904, lon: -57.141 },
    sensor_id: 5, region_id: 3,
    classifier_label: 'fire_crackle', classifier_confidence: 0.71,
    classifier_model_version: 'placeholder-v0',
    metadata: {},
    created_at: daysAgo(71), updated_at: daysAgo(68),
  },
  {
    id: 10, org_id: 1, type: 'audio', status: 'open', priority: 'medium',
    description: "Audio classifier detected 'chainsaw' with 80% confidence at TAP-01.",
    location: { lat: -5.901, lon: -57.145 },
    sensor_id: 5, region_id: 3,
    classifier_label: 'chainsaw', classifier_confidence: 0.80,
    classifier_model_version: 'placeholder-v0',
    metadata: {},
    created_at: daysAgo(43), updated_at: daysAgo(43),
  },
  {
    id: 11, org_id: 1, type: 'fusion', status: 'investigating', priority: 'high',
    description: "Fusion alert: chainsaw at TAP-01 matched selective logging NDVI signature (score 0.72). Patrol dispatched.",
    location: { lat: -5.900, lon: -57.148 },
    sensor_id: 5, region_id: 3,
    classifier_label: 'chainsaw', classifier_confidence: 0.80,
    classifier_model_version: 'placeholder-v0',
    metadata: {
      acoustic_alert_id: 10, satellite_change_id: 10,
      acoustic_confidence: 0.80, acoustic_confidence_threshold: 0.65,
      acoustic_suppressed: false, acoustic_weight: 0.45,
      satellite_severity_score: 0.41, satellite_confidence: 0.85,
      distance_meters: 31.5,
      fusion_score: 0.718, fusion_scoring_mode: 'acoustic_satellite',
      fusion_rule_version: 'rule-fusion-v2',
      temporal_decay: 0.88, spatial_decay: 0.83,
      time_decay_halflife_days: 7.0, spatial_sigma_meters: 200.0,
      corroborating_change_count: 1, source_quality_multiplier: 1.07,
      baseline_ndvi: 0.76, recent_ndvi: 0.55, ndvi_delta: -0.21, ingestion_batch_id: 3,
    },
    created_at: daysAgo(42), updated_at: daysAgo(38),
  },
  {
    id: 12, org_id: 1, type: 'audio', status: 'open', priority: 'medium',
    description: "Audio classifier detected 'vehicle' (heavy machinery) with 83% confidence at TAP-01.",
    location: { lat: -5.898, lon: -57.155 },
    sensor_id: 5, region_id: 3,
    classifier_label: 'vehicle', classifier_confidence: 0.83,
    classifier_model_version: 'placeholder-v0',
    metadata: {},
    created_at: daysAgo(20), updated_at: daysAgo(20),
  },
  {
    id: 13, org_id: 1, type: 'fusion', status: 'open', priority: 'high',
    description: "Fusion alert: sustained machinery at TAP-01 corroborates 55% severity canopy loss (score 0.78). Third detection in 21 days.",
    location: { lat: -5.896, lon: -57.159 },
    sensor_id: 5, region_id: 3,
    classifier_label: 'vehicle', classifier_confidence: 0.83,
    classifier_model_version: 'placeholder-v0',
    metadata: {
      acoustic_alert_id: 12, satellite_change_id: 11,
      acoustic_confidence: 0.83, acoustic_confidence_threshold: 0.65,
      acoustic_suppressed: false, acoustic_weight: 0.45,
      satellite_severity_score: 0.55, satellite_confidence: 0.89,
      distance_meters: 18.3,
      fusion_score: 0.783, fusion_scoring_mode: 'acoustic_satellite',
      fusion_rule_version: 'rule-fusion-v2',
      temporal_decay: 0.93, spatial_decay: 0.91,
      time_decay_halflife_days: 7.0, spatial_sigma_meters: 200.0,
      corroborating_change_count: 3, source_quality_multiplier: 1.12,
      baseline_ndvi: 0.76, recent_ndvi: 0.45, ndvi_delta: -0.31, ingestion_batch_id: 3,
    },
    created_at: daysAgo(19), updated_at: daysAgo(14),
  },
  {
    id: 14, org_id: 1, type: 'fusion', status: 'open', priority: 'critical',
    description: "CRITICAL: 72% severity Sentinel-2 detection fused with chainsaw audio at TAP-01 (score 0.86). Deforestation front now 3.8 ha.",
    location: { lat: -5.893, lon: -57.167 },
    sensor_id: 5, region_id: 3,
    classifier_label: 'chainsaw', classifier_confidence: 0.89,
    classifier_model_version: 'placeholder-v0',
    metadata: {
      acoustic_alert_id: 10, satellite_change_id: 12,
      acoustic_confidence: 0.89, acoustic_confidence_threshold: 0.65,
      acoustic_suppressed: false, acoustic_weight: 0.45,
      satellite_severity_score: 0.72, satellite_confidence: 0.92,
      distance_meters: 12.8,
      fusion_score: 0.861, fusion_scoring_mode: 'acoustic_satellite',
      fusion_rule_version: 'rule-fusion-v2',
      temporal_decay: 0.96, spatial_decay: 0.95,
      time_decay_halflife_days: 7.0, spatial_sigma_meters: 200.0,
      corroborating_change_count: 2, source_quality_multiplier: 1.14,
      baseline_ndvi: 0.76, recent_ndvi: 0.34, ndvi_delta: -0.42, ingestion_batch_id: 3,
    },
    created_at: daysAgo(2), updated_at: daysAgo(2),
  },
  // Satellite-only (no acoustic corroboration)
  {
    id: 15, org_id: 1, type: 'satellite', status: 'open', priority: 'medium',
    description: "Satellite-only: NDVI drop 0.24 in Xingu buffer zone (grid B5) — no acoustic sensor coverage. Ground verification needed.",
    location: { lat: -7.334, lon: -52.415 },
    sensor_id: null, region_id: 2,
    classifier_label: null, classifier_confidence: null, classifier_model_version: null,
    metadata: { satellite_change_id: 5, satellite_severity_score: 0.38, ingestion_batch_id: 2 },
    created_at: daysAgo(67), updated_at: daysAgo(67),
  },
  {
    id: 16, org_id: 1, type: 'satellite', status: 'acknowledged', priority: 'low',
    description: "Satellite-only: low-severity fragmentation in Tapajós northwest (grid C2). Monitoring scheduled.",
    location: { lat: -5.910, lon: -57.135 },
    sensor_id: null, region_id: 3,
    classifier_label: null, classifier_confidence: null, classifier_model_version: null,
    metadata: { satellite_change_id: 9, satellite_severity_score: 0.29, ingestion_batch_id: 3 },
    created_at: daysAgo(71), updated_at: daysAgo(65),
  },
]

export const demoNdviBatches = [
  {
    id: 1, org_id: 1, region_id: 1,
    source_type: 'csv', filename: 'araguaia_ndvi_q3.csv',
    status: 'processed', row_count: 48, created_change_count: 4,
    created_at: daysAgo(78),
  },
  {
    id: 2, org_id: 1, region_id: 2,
    source_type: 'sentinel_2', filename: 'xingu_sentinel2_mosaic.csv',
    status: 'processed', row_count: 62, created_change_count: 4,
    created_at: daysAgo(68),
  },
  {
    id: 3, org_id: 1, region_id: 3,
    source_type: 'csv', filename: 'tapajos_ndvi_patrol_upload.csv',
    status: 'processed', row_count: 55, created_change_count: 4,
    created_at: daysAgo(72),
  },
]

export const demoInvites = []

export function freshDemoState() {
  return {
    profile: structuredClone(demoProfile),
    regions: structuredClone(demoRegions),
    sensors: structuredClone(demoSensors),
    alerts: structuredClone(demoAlerts),
    satelliteChanges: structuredClone(demoSatelliteChanges),
    ndviBatches: structuredClone(demoNdviBatches),
    invites: structuredClone(demoInvites),
  }
}
